// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCukccHZf7bU0m8H_6kTARQB5W6ZU9CHwc',
    appId: '1:612484713475:web:69cfc1223c6e4123439236',
    messagingSenderId: '612484713475',
    projectId: 'd-kost',
    authDomain: 'd-kost.firebaseapp.com',
    storageBucket: 'd-kost.firebasestorage.app',
    measurementId: 'G-LN0C1HXLBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvvq2ws3atKTgOwcwWgFgfnscrEQ3GT7A',
    appId: '1:612484713475:android:d3280b571c615319439236',
    messagingSenderId: '612484713475',
    projectId: 'd-kost',
    storageBucket: 'd-kost.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_ciM9MOUeTXPVkqCJo7ApLqNS60-uWnQ',
    appId: '1:612484713475:ios:f3e7b1c4ab87a3ed439236',
    messagingSenderId: '612484713475',
    projectId: 'd-kost',
    storageBucket: 'd-kost.firebasestorage.app',
    iosBundleId: 'com.example.umkmBatik',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_ciM9MOUeTXPVkqCJo7ApLqNS60-uWnQ',
    appId: '1:612484713475:ios:f3e7b1c4ab87a3ed439236',
    messagingSenderId: '612484713475',
    projectId: 'd-kost',
    storageBucket: 'd-kost.firebasestorage.app',
    iosBundleId: 'com.example.umkmBatik',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCukccHZf7bU0m8H_6kTARQB5W6ZU9CHwc',
    appId: '1:612484713475:web:7ab7a8afafa40278439236',
    messagingSenderId: '612484713475',
    projectId: 'd-kost',
    authDomain: 'd-kost.firebaseapp.com',
    storageBucket: 'd-kost.firebasestorage.app',
    measurementId: 'G-KWF2S8T187',
  );
}
